package testsServer;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import controller.CustomerController;
import controller.DataBaseController;
import data.Command;
import data.Message;
import data.Subscriber;

import testsRunners.TestConfig;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class CustomerControllerTests {

    private static CustomerController customerController;
    
    // Static variables to pass data (like IDs) between the ordered tests
    private static int createdSubscriberId = 0;
    private static int createdCustomerId = 0;
    
    // Generate a unique username so we don't get "Duplicate Entry" errors if we run the test twice
    private static String uniqueUsername = "testUser_" + System.currentTimeMillis(); 
    private static String password = "password123";

    @BeforeAll
    static void setUpBeforeClass() throws Exception {
        System.out.println("--- Setting up DB Connection for Customer Tests ---");
        try {
            // 1. Initialize the DB Controller using the config password
            DataBaseController.initiateDBC(TestConfig.DB_PASSWORD);
            
            // 2. Ensure connection is alive by getting the instance
            DataBaseController db = DataBaseController.getInstance();
            if (db == null) {
                fail("Failed to initialize DataBaseController (Instance is null)");
            }

            // 3. VERIFY CONNECTION
            // Attempt a read-only query to force a connection check immediately.
            System.out.print("Verifying DB connection... ");
            if (db.getAllSubscribersQuery() == null) {
                System.out.println("FAILED.");
                fail("DB Connection Verification Failed! Query returned null. Check your password in TestConfig.java");
            }
            System.out.println("SUCCESS.");

        } catch (Exception e) {
            e.printStackTrace();
            fail("DB Connection Error: " + e.getMessage());
        }
    }

    @BeforeEach
    void setUp() throws Exception {
        // Initialize the controller logic before each test
        customerController = new CustomerController();
    }

    @Test
    @Order(1)
    void testAddNewSubscriber() {
        System.out.println("Test 1: Add New Subscriber");

        // Prepare content exactly as expected by addNewSubscriber:
        // [0:first, 1:last, 2:type, 3:info, 4:user, 5:pass, 6:phone, 7:email]
        ArrayList<Object> content = new ArrayList<>();
        content.add("John");              // 0: FirstName
        content.add("Doe");               // 1: LastName
        content.add("subscriber");        // 2: Type (Must match ENUM)
        content.add("Vegetarian");        // 3: PersonalInfo
        content.add(uniqueUsername);      // 4: Username
        content.add(password);            // 5: Password
        
        // Generate a random phone number to avoid duplicates
        content.add("050" + (System.currentTimeMillis() % 10000000)); // 6: Phone
        content.add(uniqueUsername + "@test.com"); // 7: Email

        Message msg = new Message();
        msg.command = Command.ADD_NEW_SUBSCRIBER;
        msg.content = content;

        // Act
        Object result = customerController.handleMessageFromServer(msg);

        // Assert
        assertNotNull(result, "Result should not be null");
        assertTrue(result instanceof Subscriber, "Result should be a Subscriber object");

        Subscriber newSub = (Subscriber) result;
        assertTrue(newSub.getSubscriberId() > 0, "Subscriber ID should be generated by DB (> 0)");
        
        // Save IDs for next tests
        createdSubscriberId = newSub.getSubscriberId();
        createdCustomerId = newSub.getCustomerId();
        
        System.out.println("Created Subscriber ID: " + createdSubscriberId);
    }

    @Test
    @Order(2)
    void testCheckLoginDetails_Success() {
        System.out.println("Test 2: Check Login (Valid)");

        // Prepare content: [0:username, 1:password]
        ArrayList<Object> content = new ArrayList<>();
        content.add(uniqueUsername);
        content.add(password);

        Message msg = new Message();
        msg.command = Command.CHECK_LOGIN_DETAILS;
        msg.content = content;

        // Act
        Object result = customerController.handleMessageFromServer(msg);

        // Assert
        assertNotNull(result, "Login should succeed");
        assertTrue(result instanceof Subscriber);
        
        Subscriber sub = (Subscriber) result;
        assertEquals(uniqueUsername, sub.getUsername());
        assertEquals(createdSubscriberId, sub.getSubscriberId());
    }

    @Test
    @Order(3)
    void testCheckLoginDetails_Failure() {
        System.out.println("Test 3: Check Login (Invalid)");

        // Prepare content with WRONG password
        ArrayList<Object> content = new ArrayList<>();
        content.add(uniqueUsername);
        content.add("WRONG_PASSWORD");

        Message msg = new Message();
        msg.command = Command.CHECK_LOGIN_DETAILS;
        msg.content = content;

        // Act
        Object result = customerController.handleMessageFromServer(msg);

        // Assert
        assertNull(result, "Login should fail and return null for wrong password");
    }

    @Test
    @Order(4)
    void testUpdateSubscriberDetails() {
        System.out.println("Test 4: Update Subscriber Details");

        // Prepare content: [0:customerId, 1:phoneNumber, 2:email]
        ArrayList<Object> content = new ArrayList<>();
        content.add(createdCustomerId);         // 0: Customer ID
        
        // --- UPDATED: Generate UNIQUE values to avoid Duplicate Entry errors ---
        String newUniquePhone = "052" + (System.currentTimeMillis() % 10000000);
        String newUniqueEmail = "updated_" + System.currentTimeMillis() + "@test.com";
        
        content.add(newUniquePhone);            // 1: New Phone
        content.add(newUniqueEmail);            // 2: New Email

        Message msg = new Message();
        msg.command = Command.UPDATE_SUBSCRIBER_DETAILS;
        msg.content = content;

        // Act
        Object result = customerController.handleMessageFromServer(msg);

        // Assert
        assertTrue(result instanceof Boolean);
        assertTrue((Boolean) result, "Update should return true");
    }

    @Test
    @Order(5)
    void testGetAllSubscribers() {
        System.out.println("Test 5: Get All Subscribers");

        // Content is ignored by getAllSubscribers, but we pass empty list to be safe
        Message msg = new Message();
        msg.command = Command.GET_ALL_SUBSCRIBERS;
        msg.content = new ArrayList<>();

        // Act
        Object result = customerController.handleMessageFromServer(msg);

        // Assert
        assertNotNull(result);
        assertTrue(result instanceof ArrayList);
        
        @SuppressWarnings("unchecked")
        ArrayList<Subscriber> list = (ArrayList<Subscriber>) result;
        
        // Verify our created user is in the list
        boolean found = false;
        for (Subscriber sub : list) {
            if (sub.getSubscriberId() == createdSubscriberId) {
                found = true;
                // --- UPDATED: Check for the dynamic email prefix ---
                assertTrue(sub.getEmail().startsWith("updated_"), "Email should have been updated in Test 4");
                break;
            }
        }
        assertTrue(found, "The created subscriber should exist in the 'All Subscribers' list");
    }
}